Restful WS Spring boot example
cloudevents/sdk-java pull request #288
Opened 2020-11-19 11:31 UTC by slinkydeveloper

Part of #125

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

2020-11-19 11:42 UTC, slinkydeveloper commented
Depends on #289

2020-11-19 13:09 UTC, dsyer requested changes
Some changes suggested inline.

2020-11-19 13:39 UTC, slinkydeveloper commented on examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/JacksonConfiguration.java
> +    @Bean
Can I remove `JerseyConfiguration` too?

2020-11-19 15:16 UTC, dsyer commented on examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/JacksonConfiguration.java
> +    @Bean
I think you need to register the `CloudEventProvider`?

2020-11-19 15:26 UTC, slinkydeveloper commented on examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/JacksonConfiguration.java
> +    @Bean
The `CloudEventsProvider` should be registered through the restful ws SPI: https://github.com/cloudevents/sdk-java/tree/master/http/restful-ws/src/main/resources/META-INF/services

2020-11-19 16:45 UTC, dsyer commented on examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/JacksonConfiguration.java
> +    @Bean
I see. Then I guess we still need it to register the `MainResource` at least? It's more common in a Spring Boot app to register the instance, not the class, but in this case it doesn't matter.

2020-11-19 16:48 UTC, slinkydeveloper commented on examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/JacksonConfiguration.java
> +    @Bean
TBH I'm not at all expert of conventions in Spring Boot, so I can't tell which solution is best... Should I change the registration with the instances?

2020-11-19 17:35 UTC, dsyer commented on examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/JacksonConfiguration.java
> +    @Bean
I don't think it matters actually. This sample does it with class literals: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-jersey/src/main/java/smoketest/jersey/JerseyConfig.java

2020-11-20 13:09 UTC, salaboy commented
@slinkydeveloper @dsyer this is good! and I think that is basically doing what I need as well.

2020-11-20 13:13 UTC, dsyer commented
@salaboy good to hear. Your PR was using Spring `@RestController` though, and I think we should have some support for that as well eventually. @olegz is working on a PR that has a `@RestController` BTW.

2020-11-20 13:25 UTC, salaboy commented
@dsyer that's cool.. I think that if webflux is supported I am more than ok with it.. I've created the @RestController stuff to create a PR to this repo, because I was aware that not everyone was into Webflux still. I am happy to see that supported in a much cleaner way.. I believe that this is a big enabler for people to use CE.

2020-11-24 07:43 UTC, merged